CREATE TABLE overall (
  ID  VARCHAR,
 LICENSE_ID  INT,
 ACCOUNT_NUMBER  INT,
 DOING_BUSINESS_AS_NAME  VARCHAR,
 ADDRESS  VARCHAR,
 CITY  VARCHAR,
 STATE VARCHAR,
 ZIP_CODE VARCHAR,
 PRECINCT NUMERIC,
 LICENSE_DESCRIPTION VARCHAR,
 BUSINESS_ACTIVITY VARCHAR,
 LICENSE_NUMBER INT,
 APPLICATION_TYPE VARCHAR,
 APPLICATION_CREATED_DATE VARCHAR,
 APPLICATION_REQUIREMENTS_COMPLETE VARCHAR,
 PAYMENT_DATE VARCHAR,
 CONDITIONAL_APPROVAL VARCHAR,
 LICENSE_TERM_START_DATE VARCHAR,
 LICENSE_TERM_EXPIRATION_DATE VARCHAR,
 LICENSE_APPROVED_FOR_ISSUANCE VARCHAR,
 DATE_ISSUED VARCHAR,
 LICENSE_STATUS VARCHAR,
 OWNER_FIRST_NAME VARCHAR,
 OWNER_LAST_NAME VARCHAR,
 TITLE VARCHAR
);
select * from overall;
















